#!/bin/sh

for sys in PU_UP PU_DOWN \
           TRIG_UP TRIG_DOWN \
           BTAG_UP BTAG_DOWN BTAG_LJET_UP BTAG_LJET_DOWN \
           BTAG_PT_UP BTAG_PT_DOWN BTAG_ETA_UP BTAG_ETA_DOWN \
           BTAG_LJET_PT_UP BTAG_LJET_PT_DOWN BTAG_LJET_ETA_UP BTAG_LJET_ETA_DOWN \
           BTAG_BEFF_UP BTAG_BEFF_DOWN BTAG_CEFF_UP BTAG_CEFF_DOWN BTAG_LEFF_UP BTAG_LEFF_DOWN; do
    ./load_Analysis -s $sys -f Nominal &
done
wait

