import FWCore.ParameterSet.Config as cms

writeNTuple = cms.EDAnalyzer('NTupleWriter',
                       PUSource = cms.InputTag("addPileupInfo"),
                       hypoKey = cms.InputTag("ttFullLepHypKinSolution","Key"),
                       genParticles = cms.InputTag("genParticles"),
                       genMET = cms.InputTag("genMET"),
                       FullLepEvent = cms.InputTag("ttFullLepEvent"),
                       src = cms.InputTag("genEvt"),
                       muons = cms.InputTag("muons"),
                       elecs = cms.InputTag("elecs"),
                       jets      = cms.InputTag("jets"),
                       met       = cms.InputTag("met"),
                       vertices  = cms.InputTag('goodOfflinePrimaryVertices'),
                       genJets       = cms.InputTag("ak5GenJets", "", "SIM"),
                       BJetIndex     = cms.InputTag("produceHadronLevelBJets", "BJetIndex"),
                       AntiBJetIndex = cms.InputTag("produceHadronLevelBJets", "AntiBJetIndex"),
                       BHadJetIndex = cms.InputTag("produceGenLevelBJets", "BHadJetIndex"),
                       AntiBHadJetIndex = cms.InputTag("produceGenLevelBJets", "AntiBHadJetIndex"),
                       BHadrons = cms.InputTag("produceGenLevelBJets", "BHadrons"),
                       AntiBHadrons = cms.InputTag("produceGenLevelBJets", "AntiBHadrons"),
                       BHadronFromTopB = cms.InputTag("produceGenLevelBJets", "BHadronFromTopB"),
                       AntiBHadronFromTopB = cms.InputTag("produceGenLevelBJets", "AntiBHadronFromTopB"),
                       BHadronVsJet = cms.InputTag("produceGenLevelBJets", "BHadronVsJet"),
                       AntiBHadronVsJet = cms.InputTag("produceGenLevelBJets", "AntiBHadronVsJet"),
                       includeTrigger = cms.bool(False),
                       triggerResults = cms.InputTag('TriggerResults','','HLT'),
                       decayMode = cms.InputTag("generatorTopFilter", "decayMode"),
                       isTtBarSample = cms.bool(True),
                       isMC = cms.bool(True),
                       sampleName = cms.string("please give sampleName"),
                       channelName = cms.string("please give channelName"),
                       systematicsName = cms.string("please give systematicsName"),
)

